import { Bebas_Neue } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";

const bebasNeue = Bebas_Neue({
  subsets: ['latin'], // specify subsets if needed
  weight: '400', // corrected weight syntax
  style: 'normal', // corrected style syntax
});

export const metadata = {
  title: "NasRock",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en" className={"bg-black"}>
      <body className={`${bebasNeue.variable} antialiased overflow-scroll bg-black scroll-smooth bg-[url('/assets/nebula.gif')] bg-fixed bg-cover bg-no-repeat `}>
      <Navbar />

      {children}
      <Footer />
      </body>
      </html>
  );
}